# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_orden', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField()),
                ('id_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='id_orden',
            field=models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='orden_detalle', to='dbms.Usuario'),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='dbms.Usuario'),
        ),
    ]
